export const GET_REQUEST = 'GET_REQUEST';

export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_FAILURE = 'GET_LOCATION_FAILURE';

export const GET_STATUS_BY_USER_INTEREST_SUCCESS =
  'GET_STATUS_BY_USER_INTEREST_SUCCESS';
export const GET_STATUS_BY_USER_INTEREST_FAILURE =
  'GET_STATUS_BY_USER_INTEREST_FAILURE';

export const GET_STATUS_DETAILS_SUCCESS = 'GET_STATUS_DETAILS_SUCCESS';
export const GET_STATUS_DETAILS_FAILURE = 'GET_STATUS_DETAILS_FAILURE';

export const GET_ALL_COMMENT_SUCCESS = 'GET_ALL_COMMENT_SUCCESS';
export const GET_ALL_COMMENT_FAILURE = 'GET_ALL_COMMENT_FAILURE';

export const GET_ALL_NOTIFICATION_BEGIN = 'GET_ALL_NOTIFICATION_BEGIN';
export const GET_ALL_NOTIFICATION_SUCCESS = 'GET_ALL_NOTIFICATION_SUCCESS';
export const GET_ALL_NOTIFICATION_FAILURE = 'GET_ALL_NOTIFICATION_FAILURE';
export const GET_INTEREST_SUCCESS = 'GET_INTEREST_SUCCESS';
export const GET_INTEREST_FAILURE = 'GET_INTEREST_FAILURE';

export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_FAILURE = 'GET_MY_PROFILE_FAILURE';

export const POST_STATUS_SUCCESS = 'POST_STATUS_SUCCESS';
export const POST_STATUS_FAILURE = 'POST_STATUS_FAILURE';

export const GET_HISTORY_POST_SUCCESS = 'GET_HISTORY_POST_SUCCESS';
export const GET_HISTORY_POST_FAILURE = 'GET_HISTORY_POST_FAILURE';

export const GET_ANOTHER_PROFILE_SUCCESS = 'GET_ANOTHER_PROFILE_SUCCESS';
export const GET_ANOTHER_PROFILE_FAILURE = 'GET_ANOTHER_PROFILE_FAILURE';

export const GET_ANOTHER_HISTORY_POST_SUCCESS = 'GET_ANOTHER_HISTORY_POST_SUCCESS';
export const GET_ANOTHER_HISTORY_POST_FAILURE = 'GET_ANOTHER_HISTORY_POST_FAILURE';

export const GET_ALL_NOTIFICATION_COUNT_SUCCESS = 'GET_ALL_NOTIFICATION_COUNT_SUCCESS';
export const GET_ALL_NOTIFICATION_COUNT_FAILURE = 'GET_ALL_NOTIFICATION_COUNT_FAILURE';

export const GET_MY_ACTIVITY_SUCCESS = 'GET_MY_ACTIVITY_SUCCESS';
export const GET_MY_ACTIVITY_FAILURE = 'GET_MY_ACTIVITY_FAILURE';

export const GET_POST_BY_INTEREST_SUCCESS = 'GET_POST_BY_INTEREST_SUCCESS';
export const GET_POST_BY_INTEREST_FAILURE = 'GET_POST_BY_INTEREST_FAILURE';

export const GET_ANOTHER_USER_ACTIVITY_SUCCESS = 'GET_ANOTHER_USER_ACTIVITY_SUCCESS';
export const GET_ANOTHER_USER_ACTIVITY_FAILURE = 'GET_ANOTHER_USER_ACTIVITY_FAILURE';

