export const GET_REQUEST = 'GET_REQUEST';

export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_FAILURE = 'GET_LOCATION_FAILURE';

export const GET_STATUS_BY_USER_INTEREST_SUCCESS =
  'GET_STATUS_BY_USER_INTEREST_SUCCESS';
export const GET_STATUS_BY_USER_INTEREST_FAILURE =
  'GET_STATUS_BY_USER_INTEREST_FAILURE';

export const GET_STATUS_DETAILS_SUCCESS = 'GET_STATUS_DETAILS_SUCCESS';
export const GET_STATUS_DETAILS_FAILURE = 'GET_STATUS_DETAILS_FAILURE';

export const GET_ALL_COMMENT_SUCCESS = 'GET_ALL_COMMENT_SUCCESS';
export const GET_ALL_COMMENT_FAILURE = 'GET_ALL_COMMENT_FAILURE';

export const GET_ALL_NOTIFICATION_BEGIN = 'GET_ALL_NOTIFICATION_BEGIN';
export const GET_ALL_NOTIFICATION_SUCCESS = 'GET_ALL_NOTIFICATION_SUCCESS';
export const GET_ALL_NOTIFICATION_FAILURE = 'GET_ALL_NOTIFICATION_FAILURE';
